#!/usr/bin/env python3

### This Source Code Form is subject to the terms of the Mozilla Public
### License, v. 2.0. If a copy of the MPL was not distributed with this
### file, You can obtain one at http://mozilla.org/MPL/2.0/.

###    Copyright 2026 (c) o6-Automation GmbH (Author: Daniel Opitz)

"""Render the bundled companion spec list from the bundle manifest.

Run ``python internal/docs/gen_bundled_specs.py`` after changing the manifest.
``--check`` reports staleness instead of writing, for CI.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PAGE = REPO_ROOT / "internal/docs" / "o6-python" / "bundled-companion-specs.md"
MANIFEST = REPO_ROOT / "src" / "o6_nodeset_compiler" / "bundle" / "manifest.json"

HEADER = r"""<!-- Generated by internal/docs/gen_bundled_specs.py — do not edit by hand. -->

# List of bundled companion specs

o6\Python dependency declarations such as `-e ns0 -e di` select XML shipped with
`ncc`. No download is needed during compilation. At runtime, shorthand uses the
companion namespaces shipped with o6\Python. Your own generated versions belong in your
project and use [custom dependency declarations](dependencies.md#custom-dependency-locations).
See [compatibility](../compatibility.md) and [dependency usage](dependencies.md).

The bundle contains 136 canonical definitions and three compatibility definitions.
The source-only entry `irdi_v1_01_0` has no corresponding runtime module and
cannot be used as bundled shorthand.

## Historical models

Names such as `irdi_v1_00` and `irdi_v1_0_0` select different model releases even
when they share a Model URI. `irdi_v1_00` also loads a supplement that supplies
missing references. You must still declare other transitive dependencies explicitly.
Use a [custom dependency](dependencies.md#custom-dependency-locations) when you
supply your own model version and runtime package.

## Versions

A blank version means the original XML does not declare one.

| Shortname | XML version | Model URI |
| --- | --- | --- |
"""


def render() -> str:
    models = json.loads(MANIFEST.read_text())["models"]
    models.sort(key=lambda model: (model["shortname"] != "ns0", model["shortname"]))
    lines = [
        f"| `{model['shortname']}` | {model['version'] or ''} | `{model['model_uri']}` |"
        for model in models
    ]
    return HEADER + "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the page is out of date instead of rewriting it",
    )
    args = parser.parse_args(argv)

    expected = render()
    current = PAGE.read_text(encoding="utf-8") if PAGE.is_file() else None

    if args.check:
        if current != expected:
            print(
                f"{PAGE.relative_to(REPO_ROOT)} is out of date; "
                "run 'python internal/docs/gen_bundled_specs.py'",
                file=sys.stderr,
            )
            return 1
        print(f"{PAGE.relative_to(REPO_ROOT)} is up to date")
        return 0

    if current == expected:
        print(f"{PAGE.relative_to(REPO_ROOT)} is already up to date")
        return 0

    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text(expected, encoding="utf-8")
    print(f"Wrote {PAGE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
